echo runs

diff --git a/.github/workflows/code-checks.yaml b/.github/workflows/code-checks.yaml
--- a/.github/workflows/code-checks.yaml
+++ b/.github/workflows/code-checks.yaml
@@ -14,63 +14,64 @@ jobs:
       contents: read
     defaults:
       run:
-        working-directory: aws-lambda-calculator
+        # working-directory: aws-lambda-calculator
         shell: bash
     steps:
 
-      - name: Pre cleanup
-        uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
-        with:
-          github-workspace: ${{ github.workspace }}
-
-      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858  # v2.10.3
-        with:
-          egress-policy: audit
-          disable-sudo: true
-
-      - name: Checkout
-        uses: actions/checkout@v4.2.2
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-          ref: feat/aws-codebuild
-
-      - run: |
-          pyenv install 3.13 || true
-          pyenv local 3.13
-
-      # - name: Setup Python
-      #   uses: actions/setup-python@v5.4.0
+      - run: echo "Hello world!"
+      # - name: Pre cleanup
+      #   uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
       #   with:
-      #     python-version-file: pyproject.toml
-      #     cache: poetry
-
-      - name: Setup poetry
-        run: |
-          python --version
-          python -m pip install --upgrade pip
-          python -m pip install poetry==2.1.1
-
-      - name: Install dependencies
-        run: python -m poetry install
-
-      - name: Lint (ruff)
-        run: |
-          python -m poetry run ruff format --check
-          python -m poetry run ruff check
-
-      - name: Types cheking (mypy)
-        run: python -m poetry run mypy --check-untyped-defs .
-
-      - name: Notify failure if checks failed
-        if: ${{ failure() }}
-        env:
-          msg: Some of the code standard checks have failed. Please run `just checks`
-            locally before pushing your changes.
-        run: |-
-          echo "::error::${msg}"
-
-      - name: Post cleanup
-        if: ${{ always() }}
-        uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
-        with:
-          github-workspace: ${{ github.workspace }}
+      #     github-workspace: ${{ github.workspace }}
+      #
+      # - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858  # v2.10.3
+      #   with:
+      #     egress-policy: audit
+      #     disable-sudo: true
+      #
+      # - name: Checkout
+      #   uses: actions/checkout@v4.2.2
+      #   with:
+      #     fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      #     ref: feat/aws-codebuild
+      #
+      # - run: |
+      #     pyenv install 3.13 || true
+      #     pyenv local 3.13
+      #
+      # # - name: Setup Python
+      # #   uses: actions/setup-python@v5.4.0
+      # #   with:
+      # #     python-version-file: pyproject.toml
+      # #     cache: poetry
+      #
+      # - name: Setup poetry
+      #   run: |
+      #     python --version
+      #     python -m pip install --upgrade pip
+      #     python -m pip install poetry==2.1.1
+      #
+      # - name: Install dependencies
+      #   run: python -m poetry install
+      #
+      # - name: Lint (ruff)
+      #   run: |
+      #     python -m poetry run ruff format --check
+      #     python -m poetry run ruff check
+      #
+      # - name: Types cheking (mypy)
+      #   run: python -m poetry run mypy --check-untyped-defs .
+      #
+      # - name: Notify failure if checks failed
+      #   if: ${{ failure() }}
+      #   env:
+      #     msg: Some of the code standard checks have failed. Please run `just checks`
+      #       locally before pushing your changes.
+      #   run: |-
+      #     echo "::error::${msg}"
+      #
+      # - name: Post cleanup
+      #   if: ${{ always() }}
+      #   uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
+      #   with:
+      #     github-workspace: ${{ github.workspace }}
diff --git a/.github/workflows/unit-tests.yaml b/.github/workflows/unit-tests.yaml
--- a/.github/workflows/unit-tests.yaml
+++ b/.github/workflows/unit-tests.yaml
@@ -19,72 +19,73 @@ jobs:
     defaults:
       run:
         shell: bash
-        working-directory: aws-lambda-calculator
+        # working-directory: aws-lambda-calculator
     steps:
 
-      - name: Pre cleanup
-        uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
-        with:
-          github-workspace: ${{ github.workspace }}
-
-      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858  # v2.10.3
-        with:
-          egress-policy: audit
-          disable-sudo: true
-
-      - name: Checkout
-        uses: actions/checkout@v4.2.2
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-          ref: feat/aws-codebuild
-
-      - run: ldd --version
-
-      - run: |
-          pyenv install 3.13 || true
-          pyenv local 3.13
-
-      # - name: Setup Python
-      #   uses: actions/setup-python@v5.4.0
+      - run: echo "Running unit tests"
+      # - name: Pre cleanup
+      #   uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
       #   with:
-      #     python-version-file: pyproject.toml
-      #     cache: poetry
-
-      - name: Setup poetry
-        run: |
-          python --version
-          python -m pip install --upgrade pip
-          python -m pip install poetry==2.1.1
-
-      - name: Install dependencies
-        run: python -m poetry install
-
-      - name: Test the new package
-        run: python -m poetry run pytest -svv tests/
-
-      - name: Coverage comment
-        id: coverage_comment
-        uses: py-cov-action/python-coverage-comment-action@v3
-        with:
-          GITHUB_TOKEN: ${{ github.token }}
-          COVERAGE_PATH: ./aws-lambda-calculator
-
-      - name: Store Pull Request comment to be posted
-        uses: actions/upload-artifact@v4
-        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
-        with:
-          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
-          name: python-coverage-comment-action
-          # If you use a different name, update COMMENT_FILENAME accordingly
-          path: python-coverage-comment-action.txt
-
-      - name: SonarQube Scan
-        uses: SonarSource/sonarqube-scan-action@v5.1.0
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-      - name: Post cleanup
-        if: ${{ always() }}
-        uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
-        with:
-          github-workspace: ${{ github.workspace }}
+      #     github-workspace: ${{ github.workspace }}
+      #
+      # - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858  # v2.10.3
+      #   with:
+      #     egress-policy: audit
+      #     disable-sudo: true
+      #
+      # - name: Checkout
+      #   uses: actions/checkout@v4.2.2
+      #   with:
+      #     fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      #     ref: feat/aws-codebuild
+      #
+      # - run: ldd --version
+      #
+      # - run: |
+      #     pyenv install 3.13 || true
+      #     pyenv local 3.13
+      #
+      # # - name: Setup Python
+      # #   uses: actions/setup-python@v5.4.0
+      # #   with:
+      # #     python-version-file: pyproject.toml
+      # #     cache: poetry
+      #
+      # - name: Setup poetry
+      #   run: |
+      #     python --version
+      #     python -m pip install --upgrade pip
+      #     python -m pip install poetry==2.1.1
+      #
+      # - name: Install dependencies
+      #   run: python -m poetry install
+      #
+      # - name: Test the new package
+      #   run: python -m poetry run pytest -svv tests/
+      #
+      # - name: Coverage comment
+      #   id: coverage_comment
+      #   uses: py-cov-action/python-coverage-comment-action@v3
+      #   with:
+      #     GITHUB_TOKEN: ${{ github.token }}
+      #     COVERAGE_PATH: ./aws-lambda-calculator
+      #
+      # - name: Store Pull Request comment to be posted
+      #   uses: actions/upload-artifact@v4
+      #   if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
+      #   with:
+      #     # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
+      #     name: python-coverage-comment-action
+      #     # If you use a different name, update COMMENT_FILENAME accordingly
+      #     path: python-coverage-comment-action.txt
+      #
+      # - name: SonarQube Scan
+      #   uses: SonarSource/sonarqube-scan-action@v5.1.0
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #
+      # - name: Post cleanup
+      #   if: ${{ always() }}
+      #   uses: zmynx/org-github-actions/.github/actions/shared/clean-workspace@main
+      #   with:
+      #     github-workspace: ${{ github.workspace }}
